sudo: false
language: python
python:
  - 3.5
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial  # Required for Python 3.7
    - python: 3.8
      dist: xenial  # Required for Python 3.8
install:
  - pip install poetry
  - poetry install -vvv
script:
  - poetry run coverage run --source=hogwarts_apitest -m pytest -v
  - poetry run coverage report -m
after_success:
  - poetry run coveralls